version: '3'
services:
  mqttserver:
    build: .
    container_name: "fpm-schedule-server"
    volumes:
      - ./source:/app/source
      - ./config.json:/app/config.json
    ports:
      - "9999:9999"
    networks:
      - fpm-network
    restart: always
networks:
  fpm-network: