version: '3'
services:
  scheduleserver:
    image: "yfsoftcom/fpm-schedule-server:latest"
    container_name: "fpm-schedule-server"
    volumes:
      - ./config.json:/app/config.json
      - ./db.lock:/app/db.lock
    ports:
      - "9999:9999"
    networks:
      - fpm-network
    restart: always
networks:
  fpm-network: